
	-----------------
	-- Final Tables from below:

	SELECT * FROM Messy.Wind.Weather A with (NOLOCK)

	
	SELECT TOP 5000 * FROM Messy.Wind.Crime A with (NOLOCK)
	   	  


	SELECT COUNT(*), MIN(A.CrimeDt), MAX(A.CrimeDt)
	FROM Messy.Wind.Crime A with (NOLOCK)
	JOIN Messy.Wind.Weather B with (NOLOCK) ON CAST(A.CrimeDt AS DATE) = B.WDate
	-- 7252438





--	DROP TABLE Messy.Wind.CrimesOrig2

SELECT TOP 50 *
	
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
-- 7,252,896
-- 2001 - 2020


SELECT TOP 50 
	A.Date
	,CAST(A.Date AS datetime)
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)

SELECT 
	COUNT(*)							-- 7,252,896
	,COUNT(DISTINCT A.ID)				-- 7,252,896
	,COUNT(DISTINCT A.[Case Number])	-- 7,252,438
	,COUNT(DISTINCT A.Block)						-- 402
	,COUNT(DISTINCT A.IUCR)						-- 402
	,COUNT(DISTINCT A.[Primary Type])			-- 36
	,COUNT(DISTINCT A.Description)				-- 525	534
	,COUNT(DISTINCT A.[Location Description])	-- 220	215
	,COUNT(DISTINCT A.Arrest)					-- 67	2
	,COUNT(DISTINCT A.Domestic)					-- 95	2
	,COUNT(DISTINCT A.Beat)						-- 373	304
	,COUNT(DISTINCT A.District)					-- 297	25
	,COUNT(DISTINCT A.Ward)						-- 375	51
	,COUNT(DISTINCT A.[Community Area])			-- 363	79
	,COUNT(DISTINCT A.[FBI Code])				-- 165	26
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)


SELECT COUNT(*), A.Arrest
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.Arrest
ORDER BY COUNT(*) DESC

SELECT COUNT(*), A.[Primary Type]
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.[Primary Type]
ORDER BY COUNT(*) DESC

SELECT COUNT(*), A.[Community Area]
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.[Community Area]
ORDER BY COUNT(*) DESC

SELECT TOP 500 *
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
WHERE A.Arrest = ' PUBLIC'

SELECT TOP 500 
	A.[Case Number], COUNT(*)
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.[Case Number]
HAVING COUNT(*) > 1

SELECT TOP 500 
	A.[Case Number], A.[Updated On], A.ID, COUNT(*)
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.[Case Number], A.[Updated On], A.ID
HAVING COUNT(*) > 1


SELECT COUNT(*), SUM(CASE WHEN A.Arrest = 'true' THEN 1 ELSE 0 END), SUM(CASE WHEN A.Arrest = 'true' THEN 1 ELSE 0 END) * 1.0 / COUNT(*), YEAR(CAST(A.Date AS datetime))
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY YEAR(CAST(A.Date AS datetime))
ORDER BY YEAR(CAST(A.Date AS datetime)) DESC


SELECT COUNT(*), A.Arrest, AVG(DATEDIFF(DAY, CAST(A.Date AS datetime), CAST(A.[Updated On] AS datetime)) * 1.0)
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.Arrest
ORDER BY COUNT(*) DESC

SELECT 
	MAX(CAST(A.Date AS datetime))
	,MIN(CAST(A.Date AS datetime))
	,MAX(CAST(A.[Updated On] AS datetime))
	,MIN(CAST(A.[Updated On] AS datetime))
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)

SELECT TOP 500 *
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
WHERE A.[Case Number] = 'HW486725'
--HY346207

SELECT COUNT(*), YEAR(CAST(A.Date AS datetime))
	,COUNT(DISTINCT A.Beat)
	,COUNT(DISTINCT A.District)
	,COUNT(DISTINCT A.Ward)
	,COUNT(DISTINCT A.[Community Area])
	,SUM(CASE WHEN A.Ward = '' THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.[Community Area] = '' THEN 1 ELSE 0 END)
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY YEAR(CAST(A.Date AS datetime))
ORDER BY YEAR(CAST(A.Date AS datetime)) DESC

SELECT TOP 500 *
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
WHERE A.[Community Area] = ''

SELECT COUNT(*), A.IUCR
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.IUCR
ORDER BY COUNT(*) DESC

SELECT COUNT(*), A.Beat
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.Beat
ORDER BY COUNT(*) DESC

SELECT COUNT(*), A.District
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.District
ORDER BY COUNT(*) DESC

SELECT COUNT(*), A.Ward
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.Ward
ORDER BY COUNT(*) DESC

SELECT COUNT(*), A.[Community Area]
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.[Community Area]
ORDER BY COUNT(*) DESC

SELECT COUNT(*), A.[FBI Code]
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.[FBI Code]
ORDER BY COUNT(*) DESC


SELECT COUNT(*), A.Longitude
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.Longitude
ORDER BY COUNT(*) DESC
-- 873K, 70K Blank

SELECT COUNT(*), A.Latitude
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.Latitude
ORDER BY COUNT(*) DESC
-- 874K, 70K Blank

SELECT COUNT(*), A.[X Coordinate]
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.[X Coordinate]
ORDER BY COUNT(*) DESC
-- 78K, 70K Blank

SELECT COUNT(*), A.[Y Coordinate]
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.[Y Coordinate]
ORDER BY COUNT(*) DESC
-- 129K, 70K Blank






----------------------------------------------


CREATE TABLE [Wind].[PrimaryType]
(
	[PrimTypeID] [int] IDENTITY(1,1) PRIMARY KEY,
	[PrimaryType] [varchar](500) NULL
)

INSERT INTO Messy.Wind.PrimaryType (PrimaryType)
	SELECT A.[Primary Type]
	FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
	GROUP BY A.[Primary Type]
	ORDER BY COUNT(*) DESC
	-- 36
	SELECT * FROM Messy.Wind.PrimaryType A with (NOLOCK)

	
CREATE TABLE [Wind].[Description]
(
	[DescID] [int] IDENTITY(1,1) PRIMARY KEY,
	[Description] [varchar](500) NULL
)

INSERT INTO Messy.Wind.[Description] ([Description])
	SELECT REPLACE(A.Description,',','')
	FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
	GROUP BY REPLACE(A.Description,',','')
	ORDER BY COUNT(*) DESC
	-- 534
	SELECT * FROM Messy.Wind.[Description] A with (NOLOCK)
	
CREATE TABLE [Wind].[LocDesc]
(
	[LocDescID] [int] IDENTITY(1,1) PRIMARY KEY,
	[LocDesc] [varchar](500) NULL
)

INSERT INTO Messy.Wind.[LocDesc] ([LocDesc])
	SELECT REPLACE(A.[Location Description],',','')
	FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
	GROUP BY REPLACE(A.[Location Description],',','')
	ORDER BY COUNT(*) DESC
	-- 534
	SELECT * FROM Messy.Wind.[LocDesc] A with (NOLOCK)



	
SELECT TOP 50 *	
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)





	SELECT --TOP 50 
		A.ID
		,[CaseNo]	= A.[Case Number]
		,[CrimeDt]	= CAST(A.Date AS datetime)
		,[UpdateDt] = CAST(A.[Updated On] AS datetime)
		,A.Block
		,C.PrimTypeID
		,D.DescID
		,E.LocDescID
		,[Arrest] = CASE WHEN A.Arrest = 'true' THEN 1 ELSE 0 END
		,[Domestic] = CASE WHEN A.Domestic = 'true' THEN 1 ELSE 0 END
		,[IUCR] = CASE WHEN A.IUCR = '' THEN NULL ELSE A.IUCR END
		,[Beat] = CASE WHEN A.Beat = '' THEN NULL ELSE A.Beat END
		,[District] = CASE WHEN A.District = '' THEN NULL ELSE A.District END
		,[Ward] = CASE WHEN A.Ward = '' THEN NULL ELSE A.Ward END
		,[CommArea] = CASE WHEN A.[Community Area] = '' THEN NULL ELSE A.[Community Area] END
		,[FBICode] = CASE WHEN A.[FBI Code] = '' THEN NULL ELSE A.[FBI Code] END
		--,A.
	INTO Messy.Wind.Crime
	-- SELECT COUNT(*)
	FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
	JOIN (	-- Get Recent ID
			SELECT A.[Case Number], [ID] = MAX(A.ID)
			FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
			JOIN (	-- Get Recent Update Date
					SELECT A.[Case Number], [Updated On] = MAX(a.[Updated On])
					FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
					GROUP BY A.[Case Number]
				) B ON A.[Case Number] = B.[Case Number] AND A.[Updated On] = b.[Updated On]
			GROUP BY A.[Case Number]
		) B ON A.[Case Number] = B.[Case Number] AND A.ID = B.ID
	LEFT JOIN Messy.Wind.PrimaryType C with (NOLOCK) ON A.[Primary Type] = C.PrimaryType
	LEFT JOIN Messy.Wind.Description D with (NOLOCK) ON A.Description = D.Description
	LEFT JOIN Messy.Wind.LocDesc E with (NOLOCK) ON A.[Location Description] = E.LocDesc
	-- 7,252,896
	-- 7,252,438 -- Uniq CaseNo
	-- TIME: 1.08





-----------------------------------------------------------------------
-----------------------------------------------------------------------
-----------------------------------------------------------------------
-----------------------------------------------------------------------


SELECT C.name, COUNT(*), MAX(A.name), MIN(A.name)
FROM Messy.sys.tables A with (NOLOCK)
JOIN Messy.sys.schemas B with (NOLOCK) ON A.schema_id = B.schema_id
JOIN Messy.sys.columns C with (NOLOCK) ON A.object_id = C.object_id
WHERE B.name = 'Wind' AND A.name LIKE '%Weath%'
GROUP BY C.name
ORDER BY C.name

SELECT A.name
FROM Messy.sys.tables A with (NOLOCK)
JOIN Messy.sys.schemas B with (NOLOCK) ON A.schema_id = B.schema_id
WHERE B.name = 'Wind' AND A.name LIKE '%Weath%'

/*
Weath00_01	-- 14
Weath02_03	-- 16
Weath04_05	-- 16
Weath06_07	-- 98
Weath08_09	-- 168
Weath10_11	-- 179
Weath12_13
Weath14_15
Weath16_17
Weath18_19
Weath20
*/


SELECT COUNT(*)
	--,COUNT(DISTINCT A.["STATION"])
	,COUNT(DISTINCT A.STATION)
FROM Messy.Wind.Weath12_13 A with (NOLOCK)



CREATE TABLE [Wind].[WeathAll]
(
	[WID] [bigint] IDENTITY(1,1) PRIMARY KEY,
	[STATION] [varchar](50) NULL,
	[WDate] [date] NULL,
	[AWND] DECIMAL(5,2) NULL,
	[MDPR] DECIMAL(5,2) NULL,
	[PRCP] DECIMAL(5,2) NULL,
	[SNOW] DECIMAL(5,2) NULL,
	[SNWD] DECIMAL(5,2) NULL,
	[TAVG] DECIMAL(5,2) NULL,
	[TMAX] DECIMAL(5,2) NULL,
	[TMIN] DECIMAL(5,2) NULL
)


SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.WeathAll A with (NOLOCK)


	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.["STATION"]
		,CAST(A.["DATE"] AS Date)
		,CASE WHEN A.["AWND"] = '' THEN NULL ELSE CAST(A.["AWND"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["MDPR"] = '' THEN NULL ELSE CAST(A.["MDPR"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["PRCP"] = '' THEN NULL ELSE CAST(A.["PRCP"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["SNOW"] = '' THEN NULL ELSE CAST(A.["SNOW"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["SNWD"] = '' THEN NULL ELSE CAST(A.["SNWD"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["TAVG"] = '' THEN NULL ELSE CAST(A.["TAVG"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["TMAX"] = '' THEN NULL ELSE CAST(A.["TMAX"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["TMIN"] = '' THEN NULL ELSE CAST(A.["TMIN"] AS DECIMAL(4,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath00_01 A with (NOLOCK)
	-- 9681
	

INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath02_03 A with (NOLOCK)
	-- 10675
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath04_05 A with (NOLOCK)
	-- 10000
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.["STATION"]
		,CAST(A.["DATE"] AS Date)
		,CASE WHEN A.["AWND"] = '' THEN NULL ELSE CAST(A.["AWND"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["MDPR"] = '' THEN NULL ELSE CAST(A.["MDPR"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["PRCP"] = '' THEN NULL ELSE CAST(A.["PRCP"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["SNOW"] = '' THEN NULL ELSE CAST(A.["SNOW"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["SNWD"] = '' THEN NULL ELSE CAST(A.["SNWD"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["TAVG"] = '' THEN NULL ELSE CAST(A.["TAVG"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["TMAX"] = '' THEN NULL ELSE CAST(A.["TMAX"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["TMIN"] = '' THEN NULL ELSE CAST(A.["TMIN"] AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath06_07 A with (NOLOCK)
	-- 28539
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.["STATION"]
		,CAST(A.["DATE"] AS Date)
		,CASE WHEN A.["AWND"] = '' THEN NULL ELSE CAST(A.["AWND"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["MDPR"] = '' THEN NULL ELSE CAST(A.["MDPR"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["PRCP"] = '' THEN NULL ELSE CAST(A.["PRCP"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["SNOW"] = '' THEN NULL ELSE CAST(A.["SNOW"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["SNWD"] = '' THEN NULL ELSE CAST(A.["SNWD"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["TAVG"] = '' THEN NULL ELSE CAST(A.["TAVG"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["TMAX"] = '' THEN NULL ELSE CAST(A.["TMAX"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["TMIN"] = '' THEN NULL ELSE CAST(A.["TMIN"] AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath08_09 A with (NOLOCK)
	-- 68500
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath10_11 A with (NOLOCK)
	-- 78025
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath12_13 A with (NOLOCK)
	-- 83582
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath14_15 A with (NOLOCK)
	-- 76222
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath16_17 A with (NOLOCK)
	-- 77166
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath18_19 A with (NOLOCK)
	-- 77166
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath20 A with (NOLOCK)
	-- 77166




SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath00_01 A with (NOLOCK)
--WHERE A.["STATION"] = 'USC00111577'
ORDER BY NEWID()
-- 9681,731

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath02_03 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 10675,730

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath04_05 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 10000,731

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath06_07 A with (NOLOCK)
WHERE A.["STATION"] = 'USC00111577'
-- 28539,730

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath08_09 A with (NOLOCK)
WHERE A.["STATION"] = 'USC00111577'
-- 

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath10_11 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath12_13 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath14_15 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath16_17 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath18_19 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath20 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 


SELECT TOP 50 *
FROM Messy.Wind.Weath00_01 A with (NOLOCK)
WHERE A.["STATION"] = 'USW00094846'

SELECT TOP 50 *
FROM Messy.Wind.WeathAll A with (NOLOCK)
WHERE A.STATION = 'USW00094846'


SELECT TOP 500
	A.STATION
	,COUNT(*)
	,COUNT(DISTINCT YEAR(A.WDate))
	,SUM(CASE WHEN A.AWND IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.MDPR IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.PRCP IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.SNOW IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.SNWD IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.TAVG IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.TMAX IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.TMIN IS NOT NULL THEN 1 ELSE 0 END)
FROM Messy.Wind.WeathAll A with (NOLOCK)
GROUP BY A.STATION
--ORDER BY COUNT(*) DESC
ORDER BY
	SUM(CASE WHEN A.AWND IS NOT NULL THEN 1 ELSE 0 END) +
	SUM(CASE WHEN A.MDPR IS NOT NULL THEN 1 ELSE 0 END)+
	SUM(CASE WHEN A.PRCP IS NOT NULL THEN 1 ELSE 0 END)+
	SUM(CASE WHEN A.SNOW IS NOT NULL THEN 1 ELSE 0 END)+
	SUM(CASE WHEN A.SNWD IS NOT NULL THEN 1 ELSE 0 END)+
	SUM(CASE WHEN A.TAVG IS NOT NULL THEN 1 ELSE 0 END)+
	SUM(CASE WHEN A.TMAX IS NOT NULL THEN 1 ELSE 0 END)+ 
	SUM(CASE WHEN A.TMIN IS NOT NULL THEN 1 ELSE 0 END) DESC
	

SELECT TOP 500 *
-- SELECT COUNT(*)
FROM Messy..Calendar A with (NOLOCK)
LEFT JOIN Messy.Wind.WeathAll B with (NOLOCK) ON A.Calendar_Date = B.WDate AND B.STATION = 'USW00094846'
WHERE YEAR(A.Calendar_Date) BETWEEN 2001 AND 2020
	AND B.WID IS NULL
-- 7305


	SELECT *
	FROM Messy.Wind.WeathAll A with (NOLOCK)
	WHERE A.STATION = 'USW00094846'
	
	SELECT *
	FROM Messy.Wind.Weath04_05 A with (NOLOCK)
	WHERE A.STATION = 'USW00094846'
	-- CHICAGO OHARE INTERNATIONAL AIRPORT, IL US



	SELECT --TOP 50000
		A.WDate
		,A.AWND
		,A.PRCP
		,A.SNOW
		,[SNWD] = ISNULL(A.SNWD,0.00)
		,[TAVG] = CASE WHEN A.TAVG IS NULL THEN CAST(((A.TMAX + A.TMIN) / 2) AS DECIMAL(5,2)) ELSE A.TAVG END
		,A.TMAX
		,A.TMIN
	INTO Messy.Wind.Weather
	FROM Messy.Wind.WeathAll A with (NOLOCK)
	WHERE 1=1
		AND A.STATION = 'USW00094846'
		AND A.WDate >= '2001-01-01'
		AND A.WDate < '2020-12-26'
	-- 7,299

	SELECT *
	FROM Messy.Wind.Weather A with (NOLOCK)



