
	-----------------
	-- Final Tables from below:

	SELECT * FROM Messy.Wind.Weather A with (NOLOCK)
















--	DROP TABLE Messy.Wind.CrimesOrig2

SELECT TOP 50 *
FROM Messy.Wind.CrimesOrig A with (NOLOCK)
-- 7,252,896
-- 2001 - 2020


SELECT TOP 50 
	A.Date
	,CAST(A.Date AS datetime)
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)

SELECT 
	COUNT(*)							-- 7,252,896
	,COUNT(DISTINCT A.ID)				-- 7,252,896
	,COUNT(DISTINCT A.[Case Number])	-- 7,252,438
	,COUNT(DISTINCT A.IUCR)						-- 402
	,COUNT(DISTINCT A.[Primary Type])			-- 36
	,COUNT(DISTINCT A.Description)				-- 525	534
	,COUNT(DISTINCT A.[Location Description])	-- 220	215
	,COUNT(DISTINCT A.Arrest)					-- 67	2
	,COUNT(DISTINCT A.Domestic)					-- 95	2
	,COUNT(DISTINCT A.Beat)						-- 373	304
	,COUNT(DISTINCT A.District)					-- 297	25
	,COUNT(DISTINCT A.Ward)						-- 375	51
	,COUNT(DISTINCT A.[Community Area])			-- 363	79
	,COUNT(DISTINCT A.[FBI Code])				-- 165	26
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)


SELECT COUNT(*), A.Arrest
FROM Messy.Wind.CrimesOrig A with (NOLOCK)
GROUP BY A.Arrest
ORDER BY COUNT(*) DESC

SELECT TOP 500 *
FROM Messy.Wind.CrimesOrig A with (NOLOCK)
WHERE A.Arrest = ' PUBLIC'


SELECT COUNT(*), A.Arrest
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.Arrest
ORDER BY COUNT(*) DESC

SELECT COUNT(*), A.[Community Area]
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.[Community Area]
ORDER BY COUNT(*) DESC

SELECT TOP 500 *
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
WHERE A.Arrest = ' PUBLIC'


SELECT TOP 50 *
FROM Messy.Wind.CrimesOrig A with (NOLOCK)
WHERE A.Latitude = ''


SELECT TOP 500 
	A.[Case Number], COUNT(*)
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
GROUP BY A.[Case Number]
HAVING COUNT(*) > 1


SELECT TOP 500 *
FROM Messy.Wind.CrimesOrig2 A with (NOLOCK)
WHERE A.[Case Number] = 'HW486725'
--HY346207





-----------------------------------------------------------------------
-----------------------------------------------------------------------
-----------------------------------------------------------------------
-----------------------------------------------------------------------


SELECT C.name, COUNT(*), MAX(A.name), MIN(A.name)
FROM Messy.sys.tables A with (NOLOCK)
JOIN Messy.sys.schemas B with (NOLOCK) ON A.schema_id = B.schema_id
JOIN Messy.sys.columns C with (NOLOCK) ON A.object_id = C.object_id
WHERE B.name = 'Wind' AND A.name LIKE '%Weath%'
GROUP BY C.name
ORDER BY C.name

SELECT A.name
FROM Messy.sys.tables A with (NOLOCK)
JOIN Messy.sys.schemas B with (NOLOCK) ON A.schema_id = B.schema_id
WHERE B.name = 'Wind' AND A.name LIKE '%Weath%'

/*
Weath00_01	-- 14
Weath02_03	-- 16
Weath04_05	-- 16
Weath06_07	-- 98
Weath08_09	-- 168
Weath10_11	-- 179
Weath12_13
Weath14_15
Weath16_17
Weath18_19
Weath20
*/


SELECT COUNT(*)
	--,COUNT(DISTINCT A.["STATION"])
	,COUNT(DISTINCT A.STATION)
FROM Messy.Wind.Weath12_13 A with (NOLOCK)



CREATE TABLE [Wind].[WeathAll]
(
	[WID] [bigint] IDENTITY(1,1) PRIMARY KEY,
	[STATION] [varchar](50) NULL,
	[WDate] [date] NULL,
	[AWND] DECIMAL(5,2) NULL,
	[MDPR] DECIMAL(5,2) NULL,
	[PRCP] DECIMAL(5,2) NULL,
	[SNOW] DECIMAL(5,2) NULL,
	[SNWD] DECIMAL(5,2) NULL,
	[TAVG] DECIMAL(5,2) NULL,
	[TMAX] DECIMAL(5,2) NULL,
	[TMIN] DECIMAL(5,2) NULL
)


SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.WeathAll A with (NOLOCK)


	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.["STATION"]
		,CAST(A.["DATE"] AS Date)
		,CASE WHEN A.["AWND"] = '' THEN NULL ELSE CAST(A.["AWND"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["MDPR"] = '' THEN NULL ELSE CAST(A.["MDPR"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["PRCP"] = '' THEN NULL ELSE CAST(A.["PRCP"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["SNOW"] = '' THEN NULL ELSE CAST(A.["SNOW"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["SNWD"] = '' THEN NULL ELSE CAST(A.["SNWD"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["TAVG"] = '' THEN NULL ELSE CAST(A.["TAVG"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["TMAX"] = '' THEN NULL ELSE CAST(A.["TMAX"] AS DECIMAL(4,2)) END
		,CASE WHEN A.["TMIN"] = '' THEN NULL ELSE CAST(A.["TMIN"] AS DECIMAL(4,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath00_01 A with (NOLOCK)
	-- 9681
	

INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath02_03 A with (NOLOCK)
	-- 10675
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath04_05 A with (NOLOCK)
	-- 10000
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.["STATION"]
		,CAST(A.["DATE"] AS Date)
		,CASE WHEN A.["AWND"] = '' THEN NULL ELSE CAST(A.["AWND"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["MDPR"] = '' THEN NULL ELSE CAST(A.["MDPR"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["PRCP"] = '' THEN NULL ELSE CAST(A.["PRCP"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["SNOW"] = '' THEN NULL ELSE CAST(A.["SNOW"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["SNWD"] = '' THEN NULL ELSE CAST(A.["SNWD"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["TAVG"] = '' THEN NULL ELSE CAST(A.["TAVG"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["TMAX"] = '' THEN NULL ELSE CAST(A.["TMAX"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["TMIN"] = '' THEN NULL ELSE CAST(A.["TMIN"] AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath06_07 A with (NOLOCK)
	-- 28539
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.["STATION"]
		,CAST(A.["DATE"] AS Date)
		,CASE WHEN A.["AWND"] = '' THEN NULL ELSE CAST(A.["AWND"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["MDPR"] = '' THEN NULL ELSE CAST(A.["MDPR"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["PRCP"] = '' THEN NULL ELSE CAST(A.["PRCP"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["SNOW"] = '' THEN NULL ELSE CAST(A.["SNOW"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["SNWD"] = '' THEN NULL ELSE CAST(A.["SNWD"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["TAVG"] = '' THEN NULL ELSE CAST(A.["TAVG"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["TMAX"] = '' THEN NULL ELSE CAST(A.["TMAX"] AS DECIMAL(5,2)) END
		,CASE WHEN A.["TMIN"] = '' THEN NULL ELSE CAST(A.["TMIN"] AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath08_09 A with (NOLOCK)
	-- 68500
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath10_11 A with (NOLOCK)
	-- 78025
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath12_13 A with (NOLOCK)
	-- 83582
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath14_15 A with (NOLOCK)
	-- 76222
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath16_17 A with (NOLOCK)
	-- 77166
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath18_19 A with (NOLOCK)
	-- 77166
	
INSERT INTO Messy.Wind.WeathAll (STATION,WDate, AWND, MDPR, PRCP, SNOW, SNWD, TAVG, TMAX, TMIN)
	SELECT --TOP 50 
		A.STATION
		,CAST(A.DATE AS Date)
		,CASE WHEN A.AWND = '' THEN NULL ELSE CAST(A.AWND AS DECIMAL(5,2)) END
		,CASE WHEN A.MDPR = '' THEN NULL ELSE CAST(A.MDPR AS DECIMAL(5,2)) END
		,CASE WHEN A.PRCP = '' THEN NULL ELSE CAST(A.PRCP AS DECIMAL(5,2)) END
		,CASE WHEN A.SNOW = '' THEN NULL ELSE CAST(A.SNOW AS DECIMAL(5,2)) END
		,CASE WHEN A.SNWD = '' THEN NULL ELSE CAST(A.SNWD AS DECIMAL(5,2)) END
		,CASE WHEN A.TAVG = '' THEN NULL ELSE CAST(A.TAVG AS DECIMAL(5,2)) END
		,CASE WHEN A.TMAX = '' THEN NULL ELSE CAST(A.TMAX AS DECIMAL(5,2)) END
		,CASE WHEN A.TMIN = '' THEN NULL ELSE CAST(A.TMIN AS DECIMAL(5,2)) END
	-- SELECT COUNT(*)
	FROM Messy.Wind.Weath20 A with (NOLOCK)
	-- 77166




SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath00_01 A with (NOLOCK)
--WHERE A.["STATION"] = 'USC00111577'
ORDER BY NEWID()
-- 9681,731

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath02_03 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 10675,730

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath04_05 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 10000,731

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath06_07 A with (NOLOCK)
WHERE A.["STATION"] = 'USC00111577'
-- 28539,730

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath08_09 A with (NOLOCK)
WHERE A.["STATION"] = 'USC00111577'
-- 

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath10_11 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath12_13 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath14_15 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath16_17 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath18_19 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 

SELECT TOP 50 *
-- SELECT COUNT(*)
FROM Messy.Wind.Weath20 A with (NOLOCK)
WHERE A.STATION = 'USC00111577'
-- 


SELECT TOP 50 *
FROM Messy.Wind.Weath00_01 A with (NOLOCK)
WHERE A.["STATION"] = 'USW00094846'

SELECT TOP 50 *
FROM Messy.Wind.WeathAll A with (NOLOCK)
WHERE A.STATION = 'USW00094846'


SELECT TOP 500
	A.STATION
	,COUNT(*)
	,COUNT(DISTINCT YEAR(A.WDate))
	,SUM(CASE WHEN A.AWND IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.MDPR IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.PRCP IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.SNOW IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.SNWD IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.TAVG IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.TMAX IS NOT NULL THEN 1 ELSE 0 END)
	,SUM(CASE WHEN A.TMIN IS NOT NULL THEN 1 ELSE 0 END)
FROM Messy.Wind.WeathAll A with (NOLOCK)
GROUP BY A.STATION
--ORDER BY COUNT(*) DESC
ORDER BY
	SUM(CASE WHEN A.AWND IS NOT NULL THEN 1 ELSE 0 END) +
	SUM(CASE WHEN A.MDPR IS NOT NULL THEN 1 ELSE 0 END)+
	SUM(CASE WHEN A.PRCP IS NOT NULL THEN 1 ELSE 0 END)+
	SUM(CASE WHEN A.SNOW IS NOT NULL THEN 1 ELSE 0 END)+
	SUM(CASE WHEN A.SNWD IS NOT NULL THEN 1 ELSE 0 END)+
	SUM(CASE WHEN A.TAVG IS NOT NULL THEN 1 ELSE 0 END)+
	SUM(CASE WHEN A.TMAX IS NOT NULL THEN 1 ELSE 0 END)+ 
	SUM(CASE WHEN A.TMIN IS NOT NULL THEN 1 ELSE 0 END) DESC
	

SELECT TOP 500 *
-- SELECT COUNT(*)
FROM Messy..Calendar A with (NOLOCK)
LEFT JOIN Messy.Wind.WeathAll B with (NOLOCK) ON A.Calendar_Date = B.WDate AND B.STATION = 'USW00094846'
WHERE YEAR(A.Calendar_Date) BETWEEN 2001 AND 2020
	AND B.WID IS NULL
-- 7305




	SELECT --TOP 50000
		A.WDate
		,A.AWND
		,A.PRCP
		,A.SNOW
		,[SNWD] = ISNULL(A.SNWD,0.00)
		,[TAVG] = CASE WHEN A.TAVG IS NULL THEN CAST(((A.TMAX + A.TMIN) / 2) AS DECIMAL(5,2)) ELSE A.TAVG END
		,A.TMAX
		,A.TMIN
	INTO Messy.Wind.Weather
	FROM Messy.Wind.WeathAll A with (NOLOCK)
	WHERE 1=1
		AND A.STATION = 'USW00094846'
		AND A.WDate >= '2001-01-01'
		AND A.WDate < '2020-12-26'
	-- 7,299

	SELECT *
	FROM Messy.Wind.Weather A with (NOLOCK)



